[tasks.encrypt]
description = "Encrypt file with public key"
usage = """
arg "<fileName>"
"""
run = """
#!/usr/bin/env fish
set -l fileName "{{arg(name="fileName")}}"
set -l destName "$fileName.enc"

openssl enc -aes256 -pbkdf2 -md sha-256 -in "$fileName" -out "$destName"
"""
