vd-lavc-dr=yes
vd-lavc-film-grain=gpu
gpu-shader-cache=yes
sigmoid-upscaling=yes
correct-downscaling=yes
opengl-pbo=yes
vd-queue-enable=yes
vd-queue-max-secs=3
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=256MiB
scale=lanczos
cscale=lanczos
