# ハードウェアデコード
vd-lavc-dr=yes
vd-lavc-film-grain=gpu
gpu-shader-cache=yes

# アップ/ダウンスケーリング
scale=ewa_lanczos
cscale=ewa_lanczos
scale-antiring=0.6
sigmoid-upscaling=yes
correct-downscaling=yes

# ディザリング・色深度
dither-depth=auto
dither=fruit

# デバンディング
deband=yes
deband-iterations=1
deband-threshold=35
deband-range=16

# バッファリング
vd-queue-enable=yes
vd-queue-max-secs=3
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=256MiB
