# ハードウェアデコード
vd-lavc-dr=yes
vd-lavc-film-grain=gpu
gpu-shader-cache=yes

# アップ/ダウンスケーリング
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
scale-antiring=0.6
sigmoid-upscaling=yes
correct-downscaling=yes

# ディザリング・色深度
dither-depth=10
dither=fruit

# デバンディング
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16

# バッファリング
vd-queue-enable=yes
vd-queue-max-secs=3
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=256MiB

# OpenGL
opengl-pbo=yes
