" MacVim Setting
if has('gui_running')
  if has('win32')
    source $VIMRUNTIME/delmenu.vim
    set langmenu=ja_jp.utf-8
    source $VIMRUNTIME/menu.vim
  endif


  set imdisable " Kill IME

  set guioptions& " Win: egmrLtT / MacVim-Kaoriya : egimrL / Other : aegimrLtT
  set guioptions=egimrL
  set guioptions-=mrLtT
  set guioptions+=c

  set lines=60
  set columns=200

  " MacVim
  if has('gui_macvim')
    set transparency=15
    set guifont=Cica-Regular:h14,Osaka-Mono:h14
    set guifontwide=Cica-Regular:h14,Osaka-Mono:h14
    set antialias

    if has('transparency') || exists('+transparency')
      augroup hack234
        autocmd!
        autocmd FocusGained * set transparency=10
        autocmd FocusLost * set transparency=50
      augroup END
    endif
  endif
endif
