---
version: 2
root-merkers:
  - .git/

tools:
  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-source: 'shfmt'
    format-stdin: true

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-source: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c "$XDG_CONFIG_HOME/markdownlint/config.json"'
    lint-source: 'markdownlint'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f:%l:%c %m'
      - '%f: %l: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-source: 'shellcheck'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -c "$XDG_CONFIG_HOME/yamllint/config.yml" -f parsable -'
    lint-source: 'yamllint'
    lint-stdin: true

  makefile-bake: &makefile-bake
    lint-command: 'bake format --check --verbose'
    lint-formats:
      - '%f:%l: %m'

languages:
  make:
    - <<: *makefile-bake
  dockerfile:
    - <<: *dockerfile-hadolint
  markdown:
    - <<: *markdown-markdownlint
  yaml:
    - <<: *yaml-yamllint
  sh:
    - <<: *sh-shfmt
    - <<: *sh-shellcheck
