#!/usr/bin/env sh
# check if pyenv is available
# edit: fixed redirect issue in earlier version

if test -f "/usr/local/bin/brew"; then
  BREW_BIN="/usr/local/bin/brew"
fi

if test -f "/opt/homebrew/bin/brew"; then
  BREW_BIN="/opt/homebrew/bin/brew"
fi

if test -f "/home/linuxbrew/.linuxbrew/bin/brew"; then
  BREW_BIN="/home/linuxbrew/.linuxbrew/bin/brew"
fi

if which pyenv > /dev/null 2>&1; then
  /usr/bin/env PATH="${PATH//$(pyenv root)\/shims:/}" "$BREW_BIN" "$@"
else
  "$BREW_BIN" "$@"
fi
