#!/usr/bin/env bash
if [ $# -eq 0 ]; then
  echo "Usage: brew depends <package name>"
elif [ $# -eq 1 ]; then
  brew uses --installed "$@"
else
  for PACKAGE in "$@"; do
    echo "Package: $PACKAGE"
    brew uses --installed "$PACKAGE"
  done
fi
