#!/usr/bin/env bash
CMD_NAME="$(basename $0)"
CONTAINER="jlesage/mkvtoolnix"
SUEXEC="$(id -u):$(id -g)"
PWD="$(pwd)"

docker run --rm -e SUEXEC="$SUEXEC" -v "$PWD":/app -w /app "$CONTAINER" "$CMD_NAME" "$@"
