#!/usr/bin/env bash
CMD_NAME="$(basename "$0")"
VERSION="v23.12.1"
CONTAINER="jlesage/mkvtoolnix"
SUEXEC="$(id -u):$(id -g)"
PWD="$(pwd)"

docker run --rm -e SUEXEC="$SUEXEC" -v "$PWD":/app:delegated -w /app "$CONTAINER:$VERSION" "$CMD_NAME" "$@"
