#!/usr/bin/env bash
trap exit SIGINT

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `brew-world` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if which rustup > /dev/null 2>&1; then
  rustup update
  rustup completions fish > "$HOME/.config/fish/completions/rustup.fish"
fi

if test -f "$HOME/.local/share/omf/pkg/omf/functions/omf.fish"; then
  fish -l -c "omf update"
fi

if test -f "$HOME/.config/fish/functions/fisher.fish"; then
  fish -l -c "fisher update"
fi

if which anyenv > /dev/null 2>&1; then
  anyenv update
fi

if which brew > /dev/null 2>&1; then
  brew update
  brew upgrade
  brew upgrade --cask
  brew cleanup --prune 7
fi
