#!/usr/bin/env ruby

exit EXIT_FAILURE if ARGV.empty?

VERSION = -'v0.11.0'

URL = ARGV.shift
urls = URL.split('/')

TIME = urls[-1]
ID = urls[-2]

puts "ID: #{ID}"
puts "TIME: #{TIME}"

puts "docker run --rm -v \"#{ENV['PWD']}\":/output yyoshiki41/radigo:#{VERSION} rec -id=#{ID} -s=#{TIME}"
exec("docker run --rm -v \"#{ENV['PWD']}\":/output yyoshiki41/radigo:#{VERSION} rec -id=#{ID} -s=#{TIME}")
