#!/usr/bin/env ruby

exit EXIT_FAILURE if ARGV.empty?


URL=ARGV.shift
urls = URL.split("/")


TIME=urls[-1]
ID=urls[-2]

puts ID
puts TIME

puts "docker run -it -v \"$(pwd)\"/output:/output yyoshiki41/radigo rec -id=#{ID} -s=#{TIME}"
`docker run -it -v "$(pwd)"/output:/output yyoshiki41/radigo rec -id=#{ID} -s=#{TIME}`
