#!/usr/bin/env ruby

exit EXIT_FAILURE if ARGV.empty?


URL=ARGV.shift
urls = URL.split("/")


OUTPATH="#{ENV['PWD']}/output"
TIME=urls[-1]
ID=urls[-2]

puts ID
puts TIME

puts "docker run -it -v \"#{OUTPATH}\":/output yyoshiki41/radigo rec -id=#{ID} -s=#{TIME}"
exec("docker run -it -v \"#{OUTPATH}\":/output yyoshiki41/radigo rec -id=#{ID} -s=#{TIME}")
