#!/usr/bin/env bash

if [ -z "$USER_NAME" ]; then
  echo "USAGE: USER_NAME=<username> $(basename "$0")"
  exit 1
fi

adduser --disabled-password --gecos "" "$USER_NAME"

mkdir "/home/$USER_NAME/.ssh"
chmod 700 "/home/$USER_NAME/.ssh"
curl -s https://github.com/kyohsuke.keys > "/home/$USER_NAME/.ssh/authorized_keys"
chown "$USER_NAME":"$USER_NAME" "/home/$USER_NAME" -R
loginctl enable-linger "$USER_NAME"
