#!/usr/bin/env bash

VERSION="2023.11.16"
CONTAINER="jauderho/yt-dlp"
SUEXEC="$(id -u):$(id -g)"
PWD="$(pwd)"

docker run --rm -e SUEXEC="$SUEXEC" -v "$PWD":/app:delegated -w /app "$CONTAINER:$VERSION" "$*"
