---
- name: anyenv | Detect {{ envs.name }} has already installed.
  command: "whereis {{ envs.name }}"
  register: env_path
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.anyenv/bin:{{ lookup('env', 'PATH') }}"

- name: anyenv | Install {{ envs.name }}
  when: (env_path.stdout == "")
  command: "anyenv install {{ envs.name }}"
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.anyenv/bin:{{ lookup('env', 'PATH') }}"

- name: anyenv | Detect {{ envs.name }} root directory
  shell: "{{ envs.name }} root"
  register: env_root
  check_mode: no
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.anyenv/bin:{{ lookup('env', 'PATH') }}"

- name: anyenv | Checking plugin exists
  when: envs.plugins is defined
  stat:
    path: "{{ env_root.stdout }}/plugins"
  register: plug

- name: anyenv | Make directory
  when: envs.plugins is defined and not plug.stat.exists
  shell: mkdir -p "{{ env_root.stdout }}/plugins"

- name: anyenv | Install {{ envs.name }} plugins
  when: envs.plugins is defined and not plug.stat.exists
  shell: git clone "https://github.com/{{ item }}" "{{ env_root.stdout }}/plugins/{{ item | split('/') | last }}"
  loop: "{{ envs.plugins }}"

- name: anyenv | Put {{ envs.name }} symlinks
  when: envs.symlinks is defined
  shell: "test -f {{ env_root.stdout }}/{{ item.to }} || ln -s {{ lookup('env', 'HOME') }}/.config/anyenv/{{ item.from }} {{ env_root.stdout }}/{{ item.to }}"
  loop: "{{ envs.symlinks }}"
