---
- name: brew | install indiviaual formulas
  community.general.homebrew:
    name:
      - "rename"
      - "zpaq"

- name: brew | install indiviaual casks
  community.general.homebrew_cask:
    name:
      - "imageoptim"
      - "xld"
      - "cooviewer"
      - "parallels"
      - "google-drive"
