---
- name: brew | Tap a Homebrew repository
  community.general.homebrew_tap:
    tap:
      - "kyohsuke/misc"

- name: brew | install indiviaual formulas
  community.general.homebrew:
    formula:
      - "rename"
      - "zpaq"
      - "ffmpeg"


- name: brew | install indiviaual casks
  community.general.homebrew_cask:
    cask:
      - "imageoptim"
      - "xld"
      - "parallels"
      - "google-drive"
      - "keka"

      # taps
      - "kyohsuke/misc/cooviewer"
